# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Testing documentation with Rcpp
#'
#'
#' @export
rcpp_hello_world <- function() {
    .Call('_dsmisc_rcpp_hello_world', PACKAGE = 'dsmisc')
}

